[book]
authors = ["phoenixr-codes"]
language = "en"
src = "src"
title = "mdbook-inline-highlighting"

[output.html]
smart-punctuation = false

[preprocessor.inline-highlighting]
after = ["links"]
default-language = "javascript"
